### ISSUE TITLE
عالی ولیstable نبود

### ISSUE THREAD

**Issue by barry-far** [AiGptCode/iphoneprofile#1]
سلام @AiGptCode ،

خلاقیتت داخل این پروفایل ها بی نظیر بود . خودم تست کردم و جواب بود.

payloaduuid رو توی تمام بخش ها عوض کردم البته

اما یک روزی میشه که دد شده و دوباره مجبورم برگردونم  3G

و یه مورد دیگه :
![image](https://github.com/AiGptCode/iphoneprofile/assets/143993892/1fd7e426-80f1-4087-80e9-2ed1149a264b)
پروکسی سرور چرا example.com ه

**Comment by AiGptCode** [comment]
❤️
