### ISSUE TITLE
سرفیس پرو ۷ پلاس سیم‌کارت خور 

### ISSUE THREAD

**Issue by rainyboy7** [AiGptCode/iphoneprofile#2]
سلام. اسکریپت رو میشه برای سرفیس پرو ۷ پلاس هم راه اندازی کرد ؟ متاسفانه سرفیس پروهایی که از خارج کشور وارد میشن امکان ریجستری ندارن و انتنشون بعد از یکماه می‌ره

**Comment by AiGptCode** [comment]
تست نکردم :/

**Comment by AiGptCode** [comment]
ولی شاید بشه
