### ISSUE TITLE
QA - IRMCI - HAMRAH

### ISSUE THREAD

**Issue by ariaabbasi** [AiGptCode/iphoneprofile#6]
درود بر شما
تقریبا 2 3 هفته ای هست این نوع پروفایل ها روی همراه اول کار نمیکنن
اپراتور تشخیص داده میشه اما بلاک های آنتن خالی هستند
آپدیت جدیدی قرار هست برای همراه اول بیاد؟
و اینکه آیا اطلاعاتی راجب اینکه جدیدا چیکار کردن که همراه اول نمیتونه از دکل ها آنتن بگیره هست؟

**Comment by AiGptCode** [comment]
اپدیت شد وبسایت
